// SPDX-License-Identifier: AGPL-3.0-only

interface PrivacyPageProps {
  navigate: (path: string) => void;
}

export function PrivacyPage({ navigate }: PrivacyPageProps) {
  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-8">
      <button onClick={() => navigate('')} className="text-sm text-cream-dim hover:text-cream font-mono">
        &larr; Home
      </button>
      <h1 className="font-display text-3xl text-cream">Privacy</h1>

      <div className="panel p-6 space-y-6">
        <div>
          <h2 className="font-display text-lg text-cream mb-3">Network requests this app can make</h2>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-hairline text-left">
                  <th className="py-2 pr-4 font-mono text-[10px] tracking-widest uppercase text-cream-dim">DESTINATION</th>
                  <th className="py-2 pr-4 font-mono text-[10px] tracking-widest uppercase text-cream-dim">PURPOSE</th>
                  <th className="py-2 font-mono text-[10px] tracking-widest uppercase text-cream-dim">WHEN</th>
                </tr>
              </thead>
              <tbody className="text-cream-dim">
                <tr className="border-b border-hairline/50">
                  <td className="py-2 pr-4 font-mono text-xs">huggingface.co</td>
                  <td className="py-2 pr-4">Download Whisper model weights (ONNX format)</td>
                  <td className="py-2">First use only — cached by the browser afterward</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="text-xs text-cream-dim mt-3">
            That is it. There is no other network activity. No analytics, no telemetry, no crash reporting, no beacon, no pixel.
          </p>
        </div>

        <div className="border-t border-hairline pt-6">
          <h2 className="font-display text-lg text-cream mb-3">What never leaves your device</h2>
          <ul className="space-y-2 text-sm text-cream-dim">
            <li className="flex gap-2">
              <span className="text-phosphor shrink-0">&#10003;</span>
              <span>Your audio recordings (stored in IndexedDB)</span>
            </li>
            <li className="flex gap-2">
              <span className="text-phosphor shrink-0">&#10003;</span>
              <span>Transcripts generated by the local Whisper model</span>
            </li>
            <li className="flex gap-2">
              <span className="text-phosphor shrink-0">&#10003;</span>
              <span>All analysis metrics (filler counts, pace, scores)</span>
            </li>
            <li className="flex gap-2">
              <span className="text-phosphor shrink-0">&#10003;</span>
              <span>Your settings and custom question lists</span>
            </li>
          </ul>
        </div>

        <div className="border-t border-hairline pt-6">
          <h2 className="font-display text-lg text-cream mb-3">Where data is stored</h2>
          <p className="text-sm text-cream-dim">
            Sessions and audio are stored in your browser's IndexedDB. Settings are in localStorage.
            Both are scoped to this origin and inaccessible to other sites. You can delete everything
            from Settings at any time — or simply clear site data in your browser.
          </p>
        </div>

        <div className="border-t border-hairline pt-6">
          <h2 className="font-display text-lg text-cream mb-3">Offline support</h2>
          <p className="text-sm text-cream-dim">
            After the initial model download, rhetor works entirely offline. The app shell is cached
            by a service worker, and the Whisper model is cached by the browser's Cache API.
            You can record, transcribe, and analyze without any internet connection.
          </p>
        </div>
      </div>

      <button
        onClick={() => navigate('settings')}
        className="text-sm text-vu-amber hover:underline font-mono"
      >
        Go to Settings to delete all data
      </button>
    </div>
  );
}
